clear all
close all
clc

muscles = {'TrapeziusScapula_M', 'TrapeziusScapula_S', ...
       'TrapeziusScapula_I', 'TrapeziusClavicle_S', ...
       'SerratusAnterior_I', 'SerratusAnterior_M', ...
       'SerratusAnterior_S', 'Rhomboideus_S', 'Rhomboideus_I', ....
       'LevatorScapulae', 'Coracobrachialis', 'DeltoideusClavicle_A', ...
       'DeltoideusScapula_P', 'DeltoideusScapula_M', ...
       'LatissimusDorsi_S', 'LatissimusDorsi_M', 'LatissimusDorsi_I', ...
       'PectoralisMajorClavicle_S', 'PectoralisMajorThorax_I', ...
       'PectoralisMajorThorax_M', 'TeresMajor', 'Infraspinatus_I', ...
       'Infraspinatus_S', 'PectoralisMinor', 'TeresMinor', ...
       'Subscapularis_S', 'Subscapularis_M', 'Subscapularis_I', ...
       'Supraspinatus_P', 'Supraspinatus_A', 'TRIlong', 'BIC_long', ... 
       'BIC_brevis'};
   
   for m=muscles
       load([m{:},'MomentArm.mat']);
       metaData = rmfield(metaData, 'nDOF');
       metaData = rmfield(metaData, 'nLength'); 
       metaData = rmfield(metaData, 'nMomArm'); 
       save([m{:},'MomentArm.mat'], 'metaData');
   end