def getSettings():
    settings = {                  
            '0': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'markers_toTrack':  
                    ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
                     'centijc7', 'centpxt8'],
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': True,
                
                'w_activationTerm': 0,
                'w_jointAccelerationTerm': 1,
                'w_actJExcitationTerm': 1,
                'w_gtJExcitationTerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000,
                              
                # 'norm_std': False,
                # 'boundsMarker': 'uniformBoundsMarker',
                # 'markers_as_controls': True,
                # 'markers_scaling': 3,
                # 'conservative_bounds': False
                },
            '1': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'markers_toTrack':  
                    ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
                     'centijc7', 'centpxt8'],
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                
                'w_activationTerm': 0,
                'w_jointAccelerationTerm': 1,
                'w_actJExcitationTerm': 1,
                'w_gtJExcitationTerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000,
                              
                # 'norm_std': False,
                # 'boundsMarker': 'uniformBoundsMarker',
                # 'markers_as_controls': True,
                # 'markers_scaling': 3,
                # 'conservative_bounds': False
                },
            '2': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'markers_toTrack':  
                    ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
                     'centijc7', 'centpxt8'],
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': False,
                'constraint_acc': False,
                
                'w_activationTerm': 0,
                'w_jointAccelerationTerm': 1,
                'w_actJExcitationTerm': 1,
                'w_gtJExcitationTerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000,
                              
                # 'norm_std': False,
                # 'boundsMarker': 'uniformBoundsMarker',
                # 'markers_as_controls': True,
                # 'markers_scaling': 3,
                # 'conservative_bounds': False
                },
            '3': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'markers_toTrack':  
                    ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
                     'centijc7', 'centpxt8'],
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': False,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': True,
                
                'w_activationTerm': 0,
                'w_jointAccelerationTerm': 1,
                'w_actJExcitationTerm': 1,
                'w_gtJExcitationTerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000,
                              
                # 'norm_std': False,
                # 'boundsMarker': 'uniformBoundsMarker',
                # 'markers_as_controls': True,
                # 'markers_scaling': 3,
                # 'conservative_bounds': False
                },
            '4': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'markers_toTrack':  
                    ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
                     'centijc7', 'centpxt8'],
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': False,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                
                'w_activationTerm': 0,
                'w_jointAccelerationTerm': 1,
                'w_actJExcitationTerm': 1,
                'w_gtJExcitationTerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000,
                              
                # 'norm_std': False,
                # 'boundsMarker': 'uniformBoundsMarker',
                # 'markers_as_controls': True,
                # 'markers_scaling': 3,
                # 'conservative_bounds': False
                },
            '5': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'markers_toTrack':  
                    ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
                     'centijc7', 'centpxt8'],
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': False,
                'constraint_pos': True,
                'constraint_vel': False,
                'constraint_acc': False,
                
                'w_activationTerm': 0,
                'w_jointAccelerationTerm': 1,
                'w_actJExcitationTerm': 1,
                'w_gtJExcitationTerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000,
                              
                # 'norm_std': False,
                # 'boundsMarker': 'uniformBoundsMarker',
                # 'markers_as_controls': True,
                # 'markers_scaling': 3,
                # 'conservative_bounds': False
                },
            '6': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'markers_toTrack':  
                    ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
                     'centijc7', 'centpxt8'],
                'timeInterval': [0.5, 6.5],                
                'N': 600,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                
                'w_activationTerm': 0,
                'w_jointAccelerationTerm': 1,
                'w_actJExcitationTerm': 1,
                'w_gtJExcitationTerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000,
                              
                # 'norm_std': False,
                # 'boundsMarker': 'uniformBoundsMarker',
                # 'markers_as_controls': True,
                # 'markers_scaling': 3,
                # 'conservative_bounds': False
                },
            '7': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'imus',
                'imus_toTrack':  
                    ['radius_imu_x', 'radius_imu_y', 'radius_imu_z'],
                'timeInterval': [1, 2],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_6',
                
                'w_activationTerm': 0,
                'w_jointAccelerationTerm': 1,
                'w_actJExcitationTerm': 1,
                'w_gtJExcitationTerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000,
                              
                # 'norm_std': False,
                # 'boundsMarker': 'uniformBoundsMarker',
                # 'markers_as_controls': True,
                # 'markers_scaling': 3,
                # 'conservative_bounds': False
                },
            '8': {
                'subjectID' : '0',
                'model': 'weldGT_scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'markers_toTrack':  
                    ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
                     'centijc7', 'centpxt8'],
                'timeInterval': [0.5, 6.5],                
                'N': 1000,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                
                'w_activationTerm': 0,
                'w_jointAccelerationTerm': 1,
                'w_actJExcitationTerm': 1,
                'w_gtJExcitationTerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000,
                              
                # 'norm_std': False,
                # 'boundsMarker': 'uniformBoundsMarker',
                # 'markers_as_controls': True,
                # 'markers_scaling': 3,
                # 'conservative_bounds': False
                }
                }
    return settings
