def getSettings():
    settings = {               
            # Not many changes in between, results between 0-40 cannot be trusted.
            # '0': {
            #     'subjectID' : '0',
            #     'model': 'scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'markers_toTrack':  
            #         ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
            #          'centijc7', 'centpxt8'],
            #     'timeInterval': [0.5, 1.5],                
            #     'N': 100,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': [
            #             'ground_thorax_rot_x', 'ground_thorax_rot_y',
            #             'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot',
            #             'elbow_flexion', 'pro_sup'],
            #         'translational': []},
            #     'guess_zeroVelocity': False,
            #     'guess_zeroAcceleration': False,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': True,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000,
                              
            #     # 'norm_std': False,
            #     # 'boundsMarker': 'uniformBoundsMarker',
            #     # 'markers_as_controls': True,
            #     # 'markers_scaling': 3,
            #     },
            # '1': {
            #     'subjectID' : '0',
            #     'model': 'scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 1.5],                
            #     'N': 100,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': [
            #             'ground_thorax_rot_x', 'ground_thorax_rot_y',
            #             'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot',
            #             'elbow_flexion', 'pro_sup'],
            #         'translational': []},
            #     'guess_zeroVelocity': False,
            #     'guess_zeroAcceleration': False,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '2': {
            #     'subjectID' : '0',
            #     'model': 'scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 1.5],                
            #     'N': 100,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': [
            #             'ground_thorax_rot_x', 'ground_thorax_rot_y',
            #             'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot',
            #             'elbow_flexion', 'pro_sup'],
            #         'translational': []},
            #     'guess_zeroVelocity': False,
            #     'guess_zeroAcceleration': False,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': False,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '3': {
            #     'subjectID' : '0',
            #     'model': 'scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 1.5],                
            #     'N': 100,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': [
            #             'ground_thorax_rot_x', 'ground_thorax_rot_y',
            #             'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot',
            #             'elbow_flexion', 'pro_sup'],
            #         'translational': []},
            #     'guess_zeroVelocity': False,
            #     'guess_zeroAcceleration': False,
            #     'guessType': "dataDriven",
            #     'velocity_correction': False,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': True,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '4': {
            #     'subjectID' : '0',
            #     'model': 'scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 1.5],                
            #     'N': 100,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': [
            #             'ground_thorax_rot_x', 'ground_thorax_rot_y',
            #             'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot',
            #             'elbow_flexion', 'pro_sup'],
            #         'translational': []},
            #     'guess_zeroVelocity': False,
            #     'guess_zeroAcceleration': False,
            #     'guessType': "dataDriven",
            #     'velocity_correction': False,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '5': {
            #     'subjectID' : '0',
            #     'model': 'scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 1.5],                
            #     'N': 100,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': [
            #             'ground_thorax_rot_x', 'ground_thorax_rot_y',
            #             'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot',
            #             'elbow_flexion', 'pro_sup'],
            #         'translational': []},
            #     'guess_zeroVelocity': False,
            #     'guess_zeroAcceleration': False,
            #     'guessType': "dataDriven",
            #     'velocity_correction': False,
            #     'constraint_pos': True,
            #     'constraint_vel': False,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '6': {
            #     'subjectID' : '0',
            #     'model': 'scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 6.5],                
            #     'N': 600,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': [
            #             'ground_thorax_rot_x', 'ground_thorax_rot_y',
            #             'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot',
            #             'elbow_flexion', 'pro_sup'],
            #         'translational': []},
            #     'guess_zeroVelocity': False,
            #     'guess_zeroAcceleration': False,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '7': {
            #     'subjectID' : '0',
            #     'model': 'scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'bodyFrame',
            #     'timeInterval': [1, 2],                
            #     'N': 100,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': False,
            #     'guess_zeroAcceleration': False,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_6',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '8': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'markers_toTrack':  
            #         ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
            #          'centijc7', 'centpxt8'],
            #     'timeInterval': [0.5, 6.5],                
            #     'N': 600,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot',
            #             'elbow_flexion', 'pro_sup'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '9': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'bodyFrame',
            #     'timeInterval': [1, 2],                
            #     'N': 100,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_8',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '10': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 6.5],                
            #     'N': 600,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '11': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'bodyFrame',
            #     'track_orientations': False,
            #     'timeInterval': [1.5, 2.5],                
            #     'N': 100,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_10',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '12': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'groundFrame',
            #     'track_orientations': False,
            #     'timeInterval': [1.5, 2.5],                
            #     'N': 100,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_10',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '13': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'groundFrame',
            #     'track_orientations': True,
            #     'timeInterval': [1.5, 2.5],                
            #     'N': 100,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_10',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '14': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'ABD01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [2.8, 9.8],                
            #     'N': 700,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '15': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'ABD01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'groundFrame',
            #     'track_orientations': True,
            #     'timeInterval': [3, 9.5],                
            #     'N': 650,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_14',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '16': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'ABD01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'bodyFrame',
            #     'track_orientations': False,
            #     'timeInterval': [3, 9.5],                
            #     'N': 650,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_14',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '17': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'ABD01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'groundFrame',
            #     'track_orientations': False,
            #     'timeInterval': [3, 9.5],                
            #     'N': 650,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_14',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '18': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'groundFrame',
            #     'track_orientations': True,
            #     'timeInterval': [0.7, 6.2],                
            #     'N': 550,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_10',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '19': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'bodyFrame',
            #     'track_orientations': False,
            #     'timeInterval': [0.7, 6.2],                
            #     'N': 550,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_10',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '20': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'groundFrame',
            #     'track_orientations': False,
            #     'timeInterval': [0.7, 6.2],                
            #     'N': 550,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_10',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '21': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'groundFrame',
            #     'track_orientations': True,
            #     'timeInterval': [0.7, 6.2],                
            #     'N': 550,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_10',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 5000
            #     },
            # '22': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'SHRUG01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.7, 2.7],                
            #     'N': 200,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '23': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'SHRUG01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 3.0],                
            #     'N': 250,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '24': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'SHRUG01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 3.0],                
            #     'N': 250,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 2000
            #     },
            # '25': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'SHRUG01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'groundFrame',
            #     'track_orientations': True,
            #     'timeInterval': [0.9, 2.5],                
            #     'N': 160,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_22',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '26': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'SHRUG01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'bodyFrame',
            #     'track_orientations': False,
            #     'timeInterval': [0.9, 2.5],                
            #     'N': 160,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_22',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '27': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'SHRUG01',
            #     'tracking_data': 'imus',
            #     'imus_toTrack': ['radius'],
            #     'imu_directions_toTrack': ['x', 'y', 'z'],
            #     'track_imus_frame': 'groundFrame',
            #     'track_orientations': False,
            #     'timeInterval': [0.9, 2.5],                
            #     'N': 160,
            #     'filter_coordinates_toTrack': True,
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'referenceIMUResultsCase': 'Case_22',
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '28': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [1.5, 2],                
            #     'N': 50,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'muscle-driven',
            #     'muscle_approximation': 'multi-dim-poly',
            #     'conservative_bounds': True,
            #     'filter_training_data_poly': False,
            #     'enablePassiveMuscleForces': True,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1, 
            #     'w_activationDt': 1,
            #     'w_forceDt': 1, 
            #     'w_trackingTerm': 1000
            #     },
            # '29': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [1.5, 2],                
            #     'N': 50,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'muscle-driven',
            #     'muscle_approximation': 'multi-dim-poly',
            #     'conservative_bounds': True,
            #     'filter_training_data_poly': True,
            #     'enablePassiveMuscleForces': True,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1, 
            #     'w_activationDt': 1,
            #     'w_forceDt': 1, 
            #     'w_trackingTerm': 1000
            #     },
            # '30': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [1.5, 2],                
            #     'N': 50,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'muscle-driven',
            #     'muscle_approximation': 'multi-dim-poly',
            #     'conservative_bounds': True,
            #     'filter_training_data_poly': True,
            #     'enablePassiveMuscleForces': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1, 
            #     'w_activationDt': 1,
            #     'w_forceDt': 1, 
            #     'w_trackingTerm': 1000
            #     },
            # '31': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 6.5],                
            #     'N': 600,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '32': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'ABD01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [2.8, 9.8],                
            #     'N': 700,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '33': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'SHRUG01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.7, 2.7],                
            #     'N': 200,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '34': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX02',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 7],                
            #     'N': 650,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '35': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'ABD02',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.7, 6.7],                
            #     'N': 600,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '36': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'SHRUG02',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.7, 2.7],                
            #     'N': 200,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '37': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX03',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 7],                
            #     'N': 650,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '38': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'ABD03',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.0, 6.5],                
            #     'N': 650,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # '39': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'SHRUG03',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.7, 2.7],                
            #     'N': 200,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            # # increased damping to 0.2
            # '40': {
            #     'subjectID' : '0',
            #     'model': 'weldGT_lockedEP_scaled',
            #     'trial': 'FLX01',
            #     'tracking_data': 'coordinates',
            #     'timeInterval': [0.5, 6.5],                
            #     'N': 600,
            #     'filter_coordinates_toTrack': True,
            #     'coordinates_toTrack': {
            #         'rotational': ['clav_prot', 'clav_elev',
            #             'scapula_abduction', 'scapula_elevation',
            #             'scapula_upward_rot', 'scapula_winging',
            #             'plane_elv', 'shoulder_elv', 'axial_rot'],
            #         'translational': []},
            #     'guess_zeroVelocity': True,
            #     'guess_zeroAcceleration': True,
            #     'guessType': "dataDriven",
            #     'velocity_correction': True,
            #     'constraint_pos': True,
            #     'constraint_vel': True,
            #     'constraint_acc': False,
            #     'actuation': 'torque-driven',
            #     'conservative_bounds': False,
                
            #     
            #     'w_jointAccTerm': 1,
            #     'w_actuationTerm': 1,
            #     'w_gtJETerm': 1,
            #     'w_lambdaTerm': 1,
            #     'w_gammaTerm': 1,   
            #     'w_trackingTerm': 1000
            #     },
            '41': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 6.5],                
                'N': 600,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '42': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 6.5],                
                'N': 600,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 100,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 100,   
                'w_trackingTerm': 1000
                },
            '43': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 6.5],                
                'N': 600,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 500,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '44': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 6.5],                
                'N': 600,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 1000,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '45': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 6.5],                
                'N': 1000,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '46': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX02',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 7],                
                'N': 650,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '47': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX03',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 7],                
                'N': 650,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '48': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'ABD01',
                'tracking_data': 'coordinates',
                'timeInterval': [2.8, 9.8],                
                'N': 700,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '49': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'ABD02',
                'tracking_data': 'coordinates',
                'timeInterval': [0.7, 6.7],                
                'N': 600,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '50': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'ABD03',
                'tracking_data': 'coordinates',
                'timeInterval': [0.0, 6.5],                
                'N': 650,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '51': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'SHRUG01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.7, 2.7],                
                'N': 200,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '52': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'SHRUG02',
                'tracking_data': 'coordinates',
                'timeInterval': [0.7, 2.7],                
                'N': 200,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '53': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'SHRUG03',
                'tracking_data': 'coordinates',
                'timeInterval': [0.7, 2.7],                
                'N': 200,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '54': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'ABD03',
                'tracking_data': 'coordinates',
                'timeInterval': [0.0, 1.0],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': True,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '55': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'SHRUG01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.7, 2.7],                
                'N': 200,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 1000,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '56': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'ABD02',
                'tracking_data': 'coordinates',
                'timeInterval': [0.7, 1.7],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'muscle-driven',
                'muscle_approximation': 'multi-dim-poly',
                'conservative_bounds': True,
                'filter_training_data_poly': True,
                'enablePassiveMuscleForces': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1, 
                'w_activationDt': 1,
                'w_forceDt': 1, 
                'w_trackingTerm': 1000
                },
            '57': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'ABD02',
                'tracking_data': 'coordinates',
                'timeInterval': [0.7, 2.7],                
                'N': 200,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'actuation': 'muscle-driven',
                'muscle_approximation': 'multi-dim-poly',
                'conservative_bounds': True,
                'filter_training_data_poly': True,
                'enablePassiveMuscleForces': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1, 
                'w_activationDt': 1,
                'w_forceDt': 1, 
                'w_trackingTerm': 1000
                },
            '58': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'ABD01',
                'tracking_data': 'imus',
                'imus_toTrack': ['radius'],
                'imu_directions_toTrack': ['x', 'y', 'z'],
                'track_imus_frame': 'groundFrame',
                'track_orientations': True,
                'timeInterval': [3, 9.5],                
                'N': 650,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_48',
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '59': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'ABD01',
                'tracking_data': 'imus',
                'imus_toTrack': ['radius'],
                'imu_directions_toTrack': ['x', 'y', 'z'],
                'track_imus_frame': 'groundFrame',
                'track_orientations': False,
                'timeInterval': [3, 9.5],                
                'N': 650,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_48',
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '60': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'ABD01',
                'tracking_data': 'imus',
                'imus_toTrack': ['radius'],
                'imu_directions_toTrack': ['x', 'y', 'z'],
                'track_imus_frame': 'bodyFrame',
                'track_orientations': False,
                'timeInterval': [3, 9.5],                
                'N': 650,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_48',
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '61': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'imus',
                'imus_toTrack': ['radius'],
                'imu_directions_toTrack': ['x', 'y', 'z'],
                'track_imus_frame': 'groundFrame',
                'track_orientations': True,
                'timeInterval': [0.7, 6.2],                
                'N': 550,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_48',
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '62': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'imus',
                'imus_toTrack': ['radius'],
                'imu_directions_toTrack': ['x', 'y', 'z'],
                'track_imus_frame': 'groundFrame',
                'track_orientations': False,
                'timeInterval': [0.7, 6.2],                
                'N': 550,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_48',
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '63': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'imus',
                'imus_toTrack': ['radius'],
                'imu_directions_toTrack': ['x', 'y', 'z'],
                'track_imus_frame': 'bodyFrame',
                'track_orientations': False,
                'timeInterval': [0.7, 6.2],                
                'N': 550,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_48',
                'actuation': 'torque-driven',
                'conservative_bounds': False,
                
                
                'w_jointAccTerm': 100,
                'w_actuationTerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                }
                }
    return settings
