def getSettings():
    settings = {                  
            '0': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'markers_toTrack':  
                    ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
                     'centijc7', 'centpxt8'],
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': True,
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000,
                              
                # 'norm_std': False,
                # 'boundsMarker': 'uniformBoundsMarker',
                # 'markers_as_controls': True,
                # 'markers_scaling': 3,
                # 'conservative_bounds': False
                },
            '1': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '2': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': False,
                'constraint_acc': False,
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '3': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': False,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': True,
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '4': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': False,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '5': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 1.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': False,
                'constraint_pos': True,
                'constraint_vel': False,
                'constraint_acc': False,
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '6': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 6.5],                
                'N': 600,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': [
                        'ground_thorax_rot_x', 'ground_thorax_rot_y',
                        'ground_thorax_rot_z', 'clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '7': {
                'subjectID' : '0',
                'model': 'scaled',
                'trial': 'FLX01',
                'tracking_data': 'imus',
                'imus_toTrack': ['radius'],
                'imu_directions_toTrack': ['x', 'y', 'z'],
                'track_imus_frame': 'bodyFrame',
                'timeInterval': [1, 2],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': False,
                'guess_zeroAcceleration': False,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_6',
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '8': {
                'subjectID' : '0',
                'model': 'weldGT_scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'markers_toTrack':  
                    ['ij', 'ai', 'ts', 'aa', 'gu', 'EpL', 'centelbow',
                     'centijc7', 'centpxt8'],
                'timeInterval': [0.5, 6.5],                
                'N': 600,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot',
                        'elbow_flexion', 'pro_sup'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '9': {
                'subjectID' : '0',
                'model': 'weldGT_scaled',
                'trial': 'FLX01',
                'tracking_data': 'imus',
                'imus_toTrack': ['radius'],
                'imu_directions_toTrack': ['x', 'y', 'z'],
                'track_imus_frame': 'bodyFrame',
                'timeInterval': [1, 2],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_8',
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '10': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'coordinates',
                'timeInterval': [0.5, 6.5],                
                'N': 600,
                'filter_coordinates_toTrack': True,
                'coordinates_toTrack': {
                    'rotational': ['clav_prot', 'clav_elev',
                        'scapula_abduction', 'scapula_elevation',
                        'scapula_upward_rot', 'scapula_winging',
                        'plane_elv', 'shoulder_elv', 'axial_rot'],
                    'translational': []},
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '11': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'imus',
                'imus_toTrack': ['radius'],
                'imu_directions_toTrack': ['x', 'y', 'z'],
                'track_imus_frame': 'bodyFrame',
                'timeInterval': [1.5, 2.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_10',
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '12': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'imus',
                'imus_toTrack': ['radius'],
                'imu_directions_toTrack': ['x', 'y', 'z'],
                'track_imus_frame': 'groundFrame',
                'timeInterval': [1.5, 2.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_10',
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                },
            '13': {
                'subjectID' : '0',
                'model': 'weldGT_lockedEP_scaled',
                'trial': 'FLX01',
                'tracking_data': 'imus',
                'imus_toTrack': ['radius'],
                'imu_directions_toTrack': ['x', 'y', 'z'],
                'track_imus_frame': 'groundFrame',
                'track_orientations': True,
                'timeInterval': [1.5, 2.5],                
                'N': 100,
                'filter_coordinates_toTrack': True,
                'guess_zeroVelocity': True,
                'guess_zeroAcceleration': True,
                'guessType': "dataDriven",
                'velocity_correction': True,
                'constraint_pos': True,
                'constraint_vel': True,
                'constraint_acc': False,
                'referenceIMUResultsCase': 'Case_10',
                
                'w_mATerm': 0,
                'w_jointAccTerm': 1,
                'w_actJETerm': 1,
                'w_gtJETerm': 1,
                'w_lambdaTerm': 1,
                'w_gammaTerm': 1,   
                'w_trackingTerm': 1000
                }
                }
    return settings
